field: 1305ee6d-61f8-4a68-89f1-41e1eca3d8ec # Super Content
fieldLayouts:
  c183b6ef-17c2-4e2d-9426-af52455b41c3:
    tabs:
      -
        elements:
          -
            fieldUid: 87c2ef93-d3e7-44e7-a8e6-4c27080c2439 # Column 1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 13194ad1-9fa0-4c83-8e0f-ee49b19abba7 # Column 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 62b06634-9290-4c9a-b4c4-aca9fc247651 # Column 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  62b06634-9290-4c9a-b4c4-aca9fc247651: # Column 3
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: column3
    instructions: ''
    name: 'Column 3'
    searchable: true
    settings:
      availableTransforms:
        - c909e108-dbba-45be-b6f3-1ab01fb9dfa4 # 230 px wide
        - ed995c29-9e87-49a6-aa47-d2638d854d06 # 350 px wide
        - 03a84b54-1534-4d28-ada1-8da3aac4ffc8 # 700 px wide
        - 42cc13c0-be07-41ef-85fc-893f9676f8ce # News Photo
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  87c2ef93-d3e7-44e7-a8e6-4c27080c2439: # Column 1
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: column1
    instructions: ''
    name: 'Column 1'
    searchable: true
    settings:
      availableTransforms:
        - c909e108-dbba-45be-b6f3-1ab01fb9dfa4 # 230 px wide
        - ed995c29-9e87-49a6-aa47-d2638d854d06 # 350 px wide
        - 03a84b54-1534-4d28-ada1-8da3aac4ffc8 # 700 px wide
        - 42cc13c0-be07-41ef-85fc-893f9676f8ce # News Photo
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: 42cc13c0-be07-41ef-85fc-893f9676f8ce # News Photo
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  13194ad1-9fa0-4c83-8e0f-ee49b19abba7: # Column 2
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: column2
    instructions: ''
    name: 'Column 2'
    searchable: true
    settings:
      availableTransforms:
        - c909e108-dbba-45be-b6f3-1ab01fb9dfa4 # 230 px wide
        - ed995c29-9e87-49a6-aa47-d2638d854d06 # 350 px wide
        - 03a84b54-1534-4d28-ada1-8da3aac4ffc8 # 700 px wide
        - 42cc13c0-be07-41ef-85fc-893f9676f8ce # News Photo
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: column3
name: '3 Column'
sortOrder: 2
