field: 5ef7e1b2-0b62-48f5-b7c4-3bbbfccb1d8f # Header Menu
fieldLayouts:
  81fa3281-f5b5-4d7d-9c8b-de15cf86d97c:
    tabs:
      -
        elements:
          -
            fieldUid: 0f5f6cf1-061d-43ab-9cd6-69bcd5ec3f8c # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b8be571c-6b78-43b1-9f84-236fb53e4b8b # button color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f5f6cf1-061d-43ab-9cd6-69bcd5ec3f8c: # Link
    columnSuffix: gkwjffhb
    contentColumnType: text
    fieldGroup: null
    handle: headerDirectLink
    instructions: 'The link for this button.'
    name: Link
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: asset
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  b8be571c-6b78-43b1-9f84-236fb53e4b8b: # button color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonColor
    instructions: 'Select the color this button will have'
    name: 'button color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - blue
            -
              - value
              - blue
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - purple
            -
              - value
              - purple
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - orange
            -
              - value
              - orange
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: directLink
name: 'Direct Link'
sortOrder: 2
