field: 1305ee6d-61f8-4a68-89f1-41e1eca3d8ec # Super Content
fieldLayouts:
  685dccb2-efaa-406b-9f55-98a296fe55f1:
    tabs:
      -
        elements:
          -
            fieldUid: fd1257a1-7aaf-497e-9a2c-cd50b211ba31 # pdf asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  fd1257a1-7aaf-497e-9a2c-cd50b211ba31: # pdf asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: pdfAsset
    instructions: 'Select a Pdf and it will be displayed in the page.'
    name: 'pdf asset'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - pdf
      defaultUploadLocationSource: 'volume:da359c23-2092-4bbd-8eac-96b43b9c81e6' # Title Bars
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:da359c23-2092-4bbd-8eac-96b43b9c81e6' # Title Bars
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: embedPdf
name: 'Embed Pdf'
sortOrder: 6
