field: f5e0557c-8c7e-42c3-ab0a-cd00c86c6fa6 # Social Buttons Matrix
fieldLayouts:
  263c8010-4992-4788-851c-359d457cc3aa:
    tabs:
      -
        elements:
          -
            fieldUid: 95959585-c417-49be-99f2-645ad1acbdd7 # Site Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f3fd9e56-bd84-48e3-a03a-76361879d144 # Site Url
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  95959585-c417-49be-99f2-645ad1acbdd7: # Site Name
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: siteName
    instructions: ''
    name: 'Site Name'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Facebook
            -
              - value
              - Facebook
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Twitter
            -
              - value
              - Twitter
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Instagram
            -
              - value
              - Instagram
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - GooglePlus
            -
              - value
              - GooglePlus
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - TikTok
            -
              - value
              - TikTok
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f3fd9e56-bd84-48e3-a03a-76361879d144: # Site Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: siteUrl
    instructions: 'The URL of this social media profile.'
    name: 'Site Url'
    searchable: false
    settings:
      allowCustomText: ''
      allowTarget: '1'
      allowedLinkNames:
        9: url
      autoNoReferrer: ''
      defaultLinkName: url
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
handle: list
name: 'Select From List'
sortOrder: 1
