field: 01bf0912-44d2-4323-a4ac-88295f2b0cdb # Message Matrix
fieldLayouts:
  b0bb26aa-6d82-43a6-9305-7aba659e0855:
    tabs:
      -
        elements:
          -
            fieldUid: ce557d65-4022-43ac-84af-b25c12301041 # Message Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 17844c2e-1456-4840-aed4-b72de4a7b62a # time to display
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  17844c2e-1456-4840-aed4-b72de4a7b62a: # time to display
    columnSuffix: null
    contentColumnType: smallint(2)
    fieldGroup: null
    handle: timeToDisplay
    instructions: 'The number of seconds to display this message before moving on to the next message.'
    name: 'time to display'
    searchable: false
    settings:
      decimals: 0
      defaultValue: '15'
      max: '60'
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: seconds
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ce557d65-4022-43ac-84af-b25c12301041: # Message Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: messageText
    instructions: 'The text to display in this emergency message.'
    name: 'Message Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: message
name: Message
sortOrder: 1
