field: 17c26a2d-b909-4d6f-9750-cbc118e6607b # TimeLine
fieldLayouts:
  47b791fd-5995-444d-9d78-50663abff451:
    tabs:
      -
        elements:
          -
            fieldUid: 4d61664d-dd61-416f-8874-11495d698bea # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 440da69d-2ad5-4af6-a6c8-db29f1aac763 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7854ec95-0657-4098-90aa-6f3df91f48c3 # Start Year
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 85de9344-f560-4595-8460-0a239b90cfb0 # Start Month
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 1c251faa-ce32-45eb-8313-a00acf3fd1be # Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 0c778942-0dda-485d-af46-b201116b1148 # End Year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: cfcc3c3f-c3fc-4326-beb6-0f6a3e13f833 # End Month
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 59d0f0ff-f82f-4325-b6c8-e9a4f721309d # End Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f8bda247-58f5-4bc5-8765-581ad9c42f7d # media
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c778942-0dda-485d-af46-b201116b1148: # End Year
    columnSuffix: null
    contentColumnType: smallint(4)
    fieldGroup: null
    handle: endYear
    instructions: ''
    name: 'End Year'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '3000'
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  1c251faa-ce32-45eb-8313-a00acf3fd1be: # Start Date
    columnSuffix: null
    contentColumnType: smallint(2)
    fieldGroup: null
    handle: startDate
    instructions: ''
    name: 'Start Date'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '31'
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  4d61664d-dd61-416f-8874-11495d698bea: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  59d0f0ff-f82f-4325-b6c8-e9a4f721309d: # End Date
    columnSuffix: null
    contentColumnType: smallint(2)
    fieldGroup: null
    handle: endDate
    instructions: ''
    name: 'End Date'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '31'
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  85de9344-f560-4595-8460-0a239b90cfb0: # Start Month
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: startMonth
    instructions: ''
    name: 'Start Month'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - ''
            -
              - value
              - '0'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'enero '
            -
              - value
              - '1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'febrero '
            -
              - value
              - '2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'marzo '
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'abril '
            -
              - value
              - '4'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'mayo '
            -
              - value
              - '5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'junio '
            -
              - value
              - '6'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'julio '
            -
              - value
              - '7'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'agosto '
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'septiembre '
            -
              - value
              - '9'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'octubre '
            -
              - value
              - '10'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'noviembre '
            -
              - value
              - '11'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'diciembre '
            -
              - value
              - '12'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  440da69d-2ad5-4af6-a6c8-db29f1aac763: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7854ec95-0657-4098-90aa-6f3df91f48c3: # Start Year
    columnSuffix: null
    contentColumnType: smallint(4)
    fieldGroup: null
    handle: startYear
    instructions: ''
    name: 'Start Year'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '3000'
      min: '1'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  cfcc3c3f-c3fc-4326-beb6-0f6a3e13f833: # End Month
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: endMonth
    instructions: ''
    name: 'End Month'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - ''
            -
              - value
              - '0'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'enero '
            -
              - value
              - '1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'febrero '
            -
              - value
              - '2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'marzo '
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'abril '
            -
              - value
              - '4'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'mayo '
            -
              - value
              - '5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'junio '
            -
              - value
              - '6'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'julio '
            -
              - value
              - '7'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'agosto '
            -
              - value
              - '8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'septiembre '
            -
              - value
              - '9'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'octubre '
            -
              - value
              - '10'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'noviembre '
            -
              - value
              - '11'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'diciembre '
            -
              - value
              - '12'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f8bda247-58f5-4bc5-8765-581ad9c42f7d: # media
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: media
    instructions: ''
    name: media
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:905040c6-3c99-4312-8262-9ac0ed535dcf' # Timelines
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:c6e719d1-7f5c-4f7d-bc06-b425217616c5' # Hero Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:905040c6-3c99-4312-8262-9ac0ed535dcf' # Timelines
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: slide
name: slide
sortOrder: 1
