field: 1305ee6d-61f8-4a68-89f1-41e1eca3d8ec # Super Content
fieldLayouts:
  e8df7bf3-1f44-4bd2-aecf-67c849a08996:
    tabs:
      -
        elements:
          -
            fieldUid: 9625cd2a-f553-4677-a2c1-5f90d04581d0 # columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: acdcf6ba-c408-485c-a0b7-4272857cee5a # tableData
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9625cd2a-f553-4677-a2c1-5f90d04581d0: # columns
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: columns
    instructions: 'http://www.tabulator.info/docs/4.9/data#array-initial'
    name: columns
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '10'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acdcf6ba-c408-485c-a0b7-4272857cee5a: # tableData
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: tableData
    instructions: ''
    name: tableData
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: '1'
      columnType: null
      initialRows: '10'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: tabulator
name: Tabulator
sortOrder: 9
