fieldLayouts:
  b452302f-3574-4489-877e-871ba3b0cc76:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1305ee6d-61f8-4a68-89f1-41e1eca3d8ec # Super Content
            instructions: ''
            label: Content
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4ec2e6a3-95e7-4312-b35e-5ae98f13d5ff # Title Bar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7dbb92d0-96b5-440f-aa78-2ceadcf5f062 # Gradiente de Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5a923be5-29f5-4dd3-923a-8f2b45ea9dce # Hide From Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Appearance
        sortOrder: 2
handle: comunidadNoSidebar
hasTitleField: true
name: 'No Sidebar'
section: f4a18913-5edc-4251-8ba0-e110e6e7734f # Comunidad
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
