fieldLayouts:
  4fad3639-ca6e-42d6-a603-2e9cadc6e485:
    tabs:
      -
        elements:
          -
            style: tip
            tip: "This type is for creating links in the menus.\r\nIn the menu, this entry will be a direct link to the given URL.\r\n\r\nIf a user somehow reaches this page, they will be redirect to the given url."
            type: craft\fieldlayoutelements\Tip
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 30fa8201-ef58-4cef-ac25-50fedc8a0262 # Simple Url
            instructions: ''
            label: URL
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: directLink
hasTitleField: true
name: 'Direct Link'
section: 95c39e64-34de-4b73-ae4d-49e6f296abe5 # Servicios
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
