defaultPlacement: end
fieldLayouts:
  57a88bab-8511-4ea5-b128-4b4486aa4d87:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: newsCategories
name: 'News Categories'
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    hasUrls: true
    template: null
    uriFormat: 'news-categories/{slug}'
structure:
  maxLevels: null
  uid: faaa6ab8-b1cd-4849-99b9-f79b3c79143c
