fieldLayouts:
  df474ad9-67c7-4f2c-b320-05917f3e39ab:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: documentosMunipales
hasUrls: true
name: 'Documentos Munipales'
settings:
  path: '@webroot/assets/documentosmunipales'
sortOrder: 11
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@web/assets/documentosmunipales'
