columnSuffix: null
contentColumnType: text
fieldGroup: ccaa1e02-761a-4951-99df-73a306ef75a1 # Common
handle: address
instructions: ''
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: Address
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
