columnSuffix: null
contentColumnType: string
fieldGroup: da0ca5ff-3ad9-4565-8564-049eefca43ae # DocumentosMunicipales
handle: documentosMunicipalesPdf
instructions: 'Seleccione o cargue el PDF para esta entrada.'
name: 'Documento PDF'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - pdf
  defaultUploadLocationSource: 'volume:b6050152-0896-4da0-acc4-aebaa0f67c61' # Documentos Munipales
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Seleccion un PDF'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:c6e719d1-7f5c-4f7d-bc06-b425217616c5' # Hero Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:b6050152-0896-4da0-acc4-aebaa0f67c61' # Documentos Munipales
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
