columnSuffix: null
contentColumnType: string
fieldGroup: da0ca5ff-3ad9-4565-8564-049eefca43ae # DocumentosMunicipales
handle: documentosMunicipalesAno
instructions: 'Seleccione un año para este documento'
name: Año
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - '2030'
        -
          - value
          - '2030'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2029'
        -
          - value
          - '2029'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2028'
        -
          - value
          - '2028'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2027'
        -
          - value
          - '2027'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2026'
        -
          - value
          - '2026'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2025'
        -
          - value
          - '2025'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2024'
        -
          - value
          - '2024'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2023'
        -
          - value
          - '2023'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2022'
        -
          - value
          - '2022'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '2021'
        -
          - value
          - '2021'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2020'
        -
          - value
          - '2020'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2019'
        -
          - value
          - '2019'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2018'
        -
          - value
          - '2018'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2017'
        -
          - value
          - '2017'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2016'
        -
          - value
          - '2016'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2015'
        -
          - value
          - '2015'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
