columnSuffix: nptweuax
contentColumnType: text
fieldGroup: fd1b751a-76d8-4482-944d-35a1911aefe0 # Emergency message Fields
handle: eMsgLink
instructions: 'Where this message should take the user when clicked. If anywhere.'
name: 'Emergency Message Link'
searchable: false
settings:
  allowCustomText: ''
  allowTarget: '1'
  allowedLinkNames:
    1: asset
    2: category
    3: entry
    9: url
  autoNoReferrer: ''
  defaultLinkName: entry
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              -
                - 'folder:2aad4e30-4ee2-4aa5-a10e-19efd18ca1b8'
                - 'folder:ab37320d-cc79-4db5-9f6a-48eed3d61c72'
                - 'folder:ce7aaacc-4ea8-4e7c-976f-9e7b050ba635'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:6f3c14fd-c48a-42f2-9aca-3315ed8d48ba' # Events Calendar
                - 'section:b905df78-0e1b-4ffe-b679-4e397b4e86a0' # Mayor's Office
                - 'section:43edaa29-2dff-444b-b667-f3de8602f3bb' # News
                - 'section:63dcf512-4f46-4ec5-a7f1-fa3e65deaabd' # Ordenanzas y Resoluciones
                - 'section:f4a18913-5edc-4251-8ba0-e110e6e7734f' # Comunidad
                - 'section:6d199544-d7ae-4c26-8d92-ded1eba879fa' # Gobierno
                - 'section:ab5b16dc-ca25-4b41-aaa4-8ee8407ec275' # Negocios
                - 'section:95c39e64-34de-4b73-ae4d-49e6f296abe5' # Servicios
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - '1'
            -
              - allowAliases
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
