columnSuffix: null
contentColumnType: boolean
fieldGroup: 9b66bf3b-99ef-4f61-b95b-487c92ef5c71 # Simple Fields
handle: hideFromMenu
instructions: 'If this is true, this entry will not appear in the mega-menu at the top of the page.'
name: 'Hide From Menu'
searchable: false
settings:
  default: false
  offLabel: 'Include in menu'
  onLabel: 'Disclude from menu'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
