columnSuffix: yxhuooue
contentColumnType: string
fieldGroup: 539c5f06-f749-4542-8158-c06506a470fd # ordenanzas y resoluciones
handle: serieDropdown
instructions: ''
name: Serie
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 2021-2022
        -
          - value
          - 2021-2022
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2020-2021
        -
          - value
          - 2020-2021
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 2019-2020
        -
          - value
          - 2019-2020
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2018-2019
        -
          - value
          - 2018-2019
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2017-2018
        -
          - value
          - 2017-2018
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2016-2017
        -
          - value
          - 2016-2017
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2015-2016
        -
          - value
          - 2015-2016
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2014-2015
        -
          - value
          - 2014-2015
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2013-2014
        -
          - value
          - 2013-2014
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2012-2013
        -
          - value
          - 2012-2013
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2011-2012
        -
          - value
          - 2011-2012
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2010-2011
        -
          - value
          - 2010-2011
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2009-2010
        -
          - value
          - 2009-2010
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2008-2009
        -
          - value
          - 2008-2009
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2007-2008
        -
          - value
          - 2007-2008
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2006-2007
        -
          - value
          - 2006-2007
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2005-2006
        -
          - value
          - 2005-2006
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2004-2005
        -
          - value
          - 2004-2005
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2003-2004
        -
          - value
          - 2003-2004
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2002-2003
        -
          - value
          - 2002-2003
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2001-2002
        -
          - value
          - 2001-2002
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2000-2001
        -
          - value
          - 2000-2001
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1999-2000
        -
          - value
          - 1999-2000
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1998-1999
        -
          - value
          - 1998-1999
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1997-1998
        -
          - value
          - 1997-1998
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1996-1997
        -
          - value
          - 1996-1997
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1995-1996
        -
          - value
          - 1995-1996
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1994-1995
        -
          - value
          - 1994-1995
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1993-1994
        -
          - value
          - 1993-1994
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1992-1993
        -
          - value
          - 1992-1993
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1991-1992
        -
          - value
          - 1991-1992
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1990-1991
        -
          - value
          - 1990-1991
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1989-1990
        -
          - value
          - 1989-1990
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1988-1989
        -
          - value
          - 1988-1989
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1987-1988
        -
          - value
          - 1987-1988
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1986-1987
        -
          - value
          - 1986-1987
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1985-1986
        -
          - value
          - 1985-1986
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1984-1985
        -
          - value
          - 1984-1985
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1983-1984
        -
          - value
          - 1983-1984
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1982-1983
        -
          - value
          - 1982-1983
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1981-1982
        -
          - value
          - 1981-1982
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 1980-1981
        -
          - value
          - 1980-1981
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
