columnSuffix: null
contentColumnType: string
fieldGroup: 9b66bf3b-99ef-4f61-b95b-487c92ef5c71 # Simple Fields
handle: simpleUrl
instructions: 'A link to any other page.'
name: 'Simple Url'
searchable: false
settings:
  errorMessage: 'Unable to find component class ''typedlinkfield\fields\LinkField''.'
  expectedType: typedlinkfield\fields\LinkField
  settings: '{"allowCustomText":"1","allowTarget":"1","allowedLinkNames":"*","autoNoReferrer":"","defaultLinkName":"entry","defaultText":"","enableAriaLabel":"","enableTitle":"","typeSettings":{"asset":{"sources":"*","allowCustomQuery":""},"category":{"sources":"*","allowCustomQuery":""},"entry":{"sources":"*","allowCustomQuery":""},"site":{"sites":"*"},"user":{"sources":"*","allowCustomQuery":""},"custom":{"disableValidation":"","allowAliases":""},"email":{"disableValidation":"","allowAliases":""},"tel":{"disableValidation":"","allowAliases":""},"url":{"disableValidation":"","allowAliases":""}}}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
