columnSuffix: null
contentColumnType: text
fieldGroup: 72594698-759c-415b-b779-35434559e175 # News Fields
handle: summary
instructions: 'A short summary of this article. Two, short sentences at most.'
name: Summary
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
