columnSuffix: null
contentColumnType: string
fieldGroup: 72594698-759c-415b-b779-35434559e175 # News Fields
handle: tags
instructions: ''
name: 'News Tags'
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'taggroup:5462d529-c3da-4bc1-bef4-afddf86ccaed' # news
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Tags
