fieldLayouts:
  54086b59-42fe-465b-88d7-72f48bdba407:
    tabs:
      -
        elements:
          -
            fieldUid: db1ea912-a5b6-4b74-a87b-a77e495825bc # Logo - Giant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5b03960f-6b1d-4f18-a545-2fe57993259d # giantFlower
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0c99bc9-55dd-4831-b8a3-e717dbed4e39 # Seal of Guaynabo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Images
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ad84678b-0e92-4a82-bab1-cbfd291810c8 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Address
        sortOrder: 2
handle: common
name: Common
sortOrder: 2
