fieldLayouts:
  64940d4c-3be0-4dbd-84db-7f2e67565e20:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Don''t forget to hit ''save'' to make any changes here appear on the webpage.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: aecf681d-35f7-4c12-97d9-ad30519dbffd # Show
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 01bf0912-44d2-4323-a4ac-88295f2b0cdb # Message Matrix
            instructions: ''
            label: Messages
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Emercency Message'
        sortOrder: 1
handle: emergencyMessage
name: 'Emergency Message'
sortOrder: 3
