currLabel: 'Plugin Store'
customIcon: null
enabled: '0'
handle: plugin-store
icon: plugin
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '9'
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: ''
url: plugin-store
