currLabel: Assets
customIcon: null
enabled: '1'
handle: assets
icon: assets
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 4
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
