currLabel: Assets
customIcon: ''
enabled: '0'
handle: assets
icon: assets
layout: 152d572e-0cb0-4442-b348-94bdfb341fba # legislatura
newWindow: '0'
order: '4'
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
