currLabel: Assets
customIcon: null
enabled: '0'
handle: assets
icon: assets
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '4'
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
