currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: bdaea7aa-95e5-4a75-99b6-7f50624ff2a1
newWindow: false
order: 4
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
