currLabel: Categories
customIcon: null
enabled: '0'
handle: categories
icon: categories
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '3'
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
