currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: categories
layout: bdaea7aa-95e5-4a75-99b6-7f50624ff2a1
newWindow: false
order: 3
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
