currLabel: Categories
customIcon: null
enabled: '1'
handle: categories
icon: categories
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 3
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
