currLabel: Categories
customIcon: ''
enabled: '0'
handle: categories
icon: categories
layout: 152d572e-0cb0-4442-b348-94bdfb341fba # legislatura
newWindow: '0'
order: '3'
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
