currLabel: 'Plugin Store'
customIcon: null
enabled: '1'
handle: plugin-store
icon: plugin
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 6
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: ''
url: plugin-store
