currLabel: Entries
customIcon: ''
enabled: '0'
handle: entries
icon: section
layout: 152d572e-0cb0-4442-b348-94bdfb341fba # legislatura
newWindow: '0'
order: '1'
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
