currLabel: Entries
customIcon: null
enabled: '1'
handle: entries
icon: section
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 2
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
