currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: bdaea7aa-95e5-4a75-99b6-7f50624ff2a1
newWindow: false
order: 1
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
