currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: bdaea7aa-95e5-4a75-99b6-7f50624ff2a1
newWindow: false
order: 2
prevLabel: Globals
prevUrl: globals
type: ''
url: globals
