currLabel: GraphQL
customIcon: null
enabled: '0'
handle: graphql
icon: '@appicons/graphql.svg'
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '6'
prevLabel: GraphQL
prevUrl: graphql
type: ''
url: graphql
