currLabel: 'News Articles'
customIcon: null
enabled: true
handle: newsArticles
icon: section
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: false
order: 99
prevLabel: 'News Articles'
prevUrl: /admin/entries/news
type: manual
url: /admin/entries/news
