currLabel: 'New Transición 2022 item'
customIcon: null
enabled: true
handle: newTransicion2022Item
icon: plus
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: false
order: 99
prevLabel: 'New Transición 2022 item'
prevUrl: '/admin/entries/documentosMunicipales/new?site=default'
type: manual
url: '/admin/entries/documentosMunicipales/new?site=default'
