currLabel: 'Set Emergency Messages'
customIcon: null
enabled: '1'
handle: setEmergencyMessages
icon: bell
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: false
order: '14'
prevLabel: 'Set Emergency Messages'
prevUrl: /admin/globals/emergencyMessage
type: manual
url: emergencyMessage
