currLabel: Settings
customIcon: null
enabled: '0'
handle: settings
icon: settings
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '8'
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
