currLabel: Settings
customIcon: null
enabled: '1'
handle: settings
icon: settings
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 8
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
