currLabel: Users
customIcon: null
enabled: '0'
handle: users
icon: users
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '5'
prevLabel: Users
prevUrl: users
type: ''
url: users
