currLabel: Users
customIcon: ''
enabled: '0'
handle: users
icon: users
layout: 152d572e-0cb0-4442-b348-94bdfb341fba # legislatura
newWindow: '0'
order: '5'
prevLabel: Users
prevUrl: users
type: ''
url: users
