currLabel: Utilities
customIcon: null
enabled: '0'
handle: utilities
icon: tool
layout: b317180f-95ec-4778-a9f4-8b88ba5b0ba0 # News
newWindow: '0'
order: '7'
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
