currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: bdaea7aa-95e5-4a75-99b6-7f50624ff2a1
newWindow: false
order: 7
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
