currLabel: Utilities
customIcon: ''
enabled: '0'
handle: utilities
icon: tool
layout: 152d572e-0cb0-4442-b348-94bdfb341fba # legislatura
newWindow: '0'
order: '7'
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
