currLabel: Utilities
customIcon: null
enabled: '1'
handle: utilities
icon: tool
layout: 48daf189-e7f0-426c-8c8c-eeb4c7b4c755 # Default
newWindow: '0'
order: 6
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
