defaultPlacement: end
enableVersioning: true
handle: comunidad
name: Comunidad
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: comunidad/_entry
    uriFormat: 'comunidad/{slug}'
structure:
  maxLevels: 4
  uid: c216a240-25e1-4283-9398-04da8aa9494e
type: structure
