defaultPlacement: end
enableVersioning: true
handle: eventsCalendar
name: 'Events Calendar'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: calendar/_entry
    uriFormat: 'calendar/{slug}'
type: channel
