defaultPlacement: end
enableVersioning: true
handle: gobierno
name: Gobierno
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: gobierno/_entry
    uriFormat: 'gobierno/{slug}'
structure:
  maxLevels: 3
  uid: 95157a98-6737-4652-8662-baeb97e18a07
type: structure
