defaultPlacement: end
enableVersioning: true
handle: mayorsOffice
name: 'Mayor''s Office'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'mayors-office/{slug}'
type: channel
