defaultPlacement: end
enableVersioning: true
handle: ordenanzasYResolutiones
name: 'Ordenanzas y Resoluciones'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: ordenanzas-y-resolutiones/_entry
    uriFormat: 'ordenanzas-y-resolutiones/{slug}'
type: channel
