defaultPlacement: end
enableVersioning: true
handle: servicios
name: Servicios
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7c9b6118-cd72-41b6-9ba6-c4e529aa2772: # Guaynabo
    enabledByDefault: true
    hasUrls: true
    template: servicios/_entry
    uriFormat: 'servicios/{slug}'
structure:
  maxLevels: 3
  uid: a8907b12-2336-48e9-95d4-8d2ec429aa7b
type: structure
